### ISSUE TITLE
Bug with flashing files

### ISSUE THREAD

**Issue by berkut0** [vlasovskikh/intellij-micropython#128]
Issue with uploading files included in subfolders — doubled backslash with following 'b' character transforms into special symbol (in my case). ~~And it freezes process of the uploading~~ (my bad, it's just relatively big, and in this regard, I suggest a progress bar)

And why it's doubled in some cases and not in others?

<details>
  <summary>Images</summary>
  
![изображение](https://user-images.githubusercontent.com/8849896/101475558-9e915b00-395d-11eb-8ca4-422bf482e4ec.png)
![изображение](https://user-images.githubusercontent.com/8849896/101475677-bf59b080-395d-11eb-9c4f-443539fa6725.png)
![изображение](https://user-images.githubusercontent.com/8849896/101475772-d5677100-395d-11eb-8ccc-1cf953e09160.png)

another example:

![изображение](https://user-images.githubusercontent.com/8849896/101487252-eff61600-396e-11eb-8d13-83bfeb1ca380.png)

</details>

**Comment by maro48m** [comment]
i've had the same error with MicroWebServer2 - upload of urlUtils.py crashed
All this is due to path replacement in microupload.py:
in make_dirs method path separator is replaced to '/' in line 96:
`posix_path = path.replace(os.path.sep, '/')`
but in main upload method it's not happening: lines 76 to 79:

```
if remote_dir:
      make_dirs(files, remote_dir, created_cache)
  with open(local_path, 'rb') as fd:
      files.put(remote_path, fd.read())
```
if you replace path separator in remote_path file upload will work correct:
`files.put(remote_path.replace(os.path.sep, '/'), fd.read())`

**Comment by Alienmario** [comment]
Having the same issue (ESP32).
