### ISSUE TITLE
Specify flash target directory

### ISSUE THREAD

**Issue by mctigger** [vlasovskikh/intellij-micropython#81]
Hi!

Is it possible to specify where to flash the files to?

For example with ampy I would do this 
```
ampy --port /dev/ttyUSB0 put ./src/my_file.py ./my_file.py
```

Additionally can I configure the project so that all files from `./src` get flashed to `./` on the device?

**Comment by markprins** [comment]
I have a similar issue or request/suggestion. I'm having a single project in PyCharm to manage my projects (because I found it a bit cumbersome to create venvs for everyone individually, plus every project is 100% the same).

I digged into the microupload.py and have a proof of concept for configuring the flash configurations to make the above possible.

My suggestion would be to add an extra configuration option which specifies the root path.
microupload.py already has the -C option to which this option could be passed. The default would be the project root (as is now).

In my situation I had executed the command as follows, which had the desired result:

```
(wemos) Marks-iMac:wemos_test mark $ /Users/markprins/.pyenv/versions/wemos/bin/python "/Users/markprins/Library/Application Support/PyCharm2018.3/intellij-micropython/scripts/microupload.py" -C /Users/markprins/dev/wemos/wemos_test -v /dev/tty.wchusbserial1d110 /Users/markprins/dev/wemos/wemos_test/main.py
Connecting to /dev/tty.wchusbserial1d110
Uploading files: 0% (0/1)
/Users/markprins/dev/wemos/wemos_test/main.py -> main.py
Uploading files: 100% (1/1)
Soft reboot
```

The file transferred is: `/Users/markprins/dev/wemos/wemos_test/main.py`
The project root is: `/Users/markprins/dev/wemos/`
The subfolder is: `/Users/markprins/dev/wemos/wemos_test/`
The outcome is on device is:
```
>>> ls()
     162 boot.py
   <dir> lib
    2283 main.py
```

When running the default behaviour would have resulted in:
```
>>> ls()
     162 boot.py
   <dir> lib
   <dir> wemos_test
>>> cd('wemos_test')
>>> ls()
    2283 main.py
```

**Comment by NJannasch** [comment]
push

**Comment by vlasovskikh** [comment]
I'm looking into ways to support it. See also PR #97.

**Comment by vlasovskikh** [comment]
The solution I've implemented is you can now mark the directory you want to be treated the root for your device as the **sources root** in the context menu of the directory: _"Mark Directory as | Sources Root"_.

The plugin will use the nearest **sources** root or **content** root to the file or directory you want to upload as the root folder to flash to your device. It is aligned with the behaviour of the PyCharm static code analyser for resolving imports. Consider this example:

```
my_micropython_projects/  # The directory you opened in PyCharm
    project1/
        main.py
        my_lib.py
    project2/
        main.py
        ...
```

You have multiple actual projects in one directory you opened in PyCharm. In project1/ you have your main.py and you may want to use imports of local modules like my_lib.py:

main.py
```python
import utime
import my_lib  # Unresolved reference, unless you mark project1/ as a sources root

while True:
    my_lib.scan()
    utime.sleep_ms(1000)
```

Unless you mark my_micropython_projects/project1/ as a sources root via Ctrl+Click on it and _"Mark Directory as | Sources Root"_, your import of `my_lib` will be an unresolved reference, because PyCharm won't consider it an entry on `sys.path` for resoling modules.

I will publish an updated version of the plugin soon.
