### ISSUE TITLE
Are there any plans for ESP32 support?

### ISSUE THREAD

**Issue by mawg** [vlasovskikh/intellij-micropython#94]
I think that ESP32 must be pretty popular by now. Are there any plans for support?

**Comment by oinsd** [comment]
I want to ask that too.

**Comment by ivkond** [comment]
https://github.com/vlasovskikh/intellij-micropython/pull/88

**Comment by MathyV** [comment]
It just works if you select the ESP8266 device type, which makes sense as basically they're both running MicroPython. The referenced pull request doesn't actually add anything for ESP32 support as far as I can tell, it just replaces the usage of adafruit-ampy.

The only thing that could be added is probably better code hints for ESP32 but since I just started using the ESP32 myself I have no idea if they differ that much from ESP8266.

**Comment by vlasovskikh** [comment]
Yes, there are, follow #44.
